#!/bin/sh
#THIS SCRIPT WILL "MOST LIKELY" ONLY WORK ON THE CC SERVER
if [ -n "$1" ]; then
        ssh web@develop.fyens.dk "svn delete \$SVNROOT/$1/tags/latest -m 'Removed old latest tag from: $1'"
        ssh web@develop.fyens.dk "svn copy \$SVNROOT/$1/trunk \$SVNROOT/$1/tags/latest -m 'Tagged latest successful build: $1'"
else
        echo 'Missing module'
fi